export * from "./types";
export { services } from "./services";
export { industries } from "./industries";
export { solutions } from "./solutions";
export { processSteps } from "./process";
export { testimonials } from "./testimonials";
export { stats } from "./stats";
export { whyChooseUs } from "./why-choose-us";
export { techStack } from "./tech-stack";
export { roles } from "./roles";
export { engagementModels } from "./engagement-models";
export { faq } from "./faq";
export { footerConfig } from "./footer";
