import type { Metadata } from "next";

export const siteMetadata = {
  title: "YJ Ventures: AI Automation, Multi-Agent Workflows and Custom SaaS",
  description:
    "We build AI automation and multi-agent workflows that turn manual work into one intelligent system. Serving 9 industries across five continents. Book a demo.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://yjventures.in",
};

// OG images are generated by app/opengraph-image.tsx (file convention),
// so we omit explicit `images` from metadata to let the convention apply.
export const rootMetadata: Metadata = {
  title: {
    default: siteMetadata.title,
    template: "%s | YJ Ventures",
  },
  description: siteMetadata.description,
  metadataBase: new URL(siteMetadata.url),
  alternates: { canonical: "/" },
  openGraph: {
    title: siteMetadata.title,
    description: siteMetadata.description,
    url: siteMetadata.url,
    siteName: "YJ Ventures",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: siteMetadata.title,
    description: siteMetadata.description,
  },
};

export function pageMetadata(
  title: string,
  description: string,
  path: string,
): Metadata {
  const url = `${siteMetadata.url}${path}`;
  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title,
      description,
      url,
      siteName: "YJ Ventures",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
    },
  };
}
